server:
  port: 3001
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: source-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/source/**

management:
  endpoints:
    web:
      exposure:
        include: "*"