server:
  port: 3001
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false
        registerHealthCheck: false
    gateway:
      discovery:
        locator:
          enabled: true
          predicates:
            - name: Path
              args:
                pattern: "'/services/'+serviceId.toLowerCase()+'/**'"
          filters:
            - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: "*"