server:
  port: 3001
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false
        registerHealthCheck: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: consul-client
          uri: http://localhost:999
          predicates:
            - Path=/test/consul-client/**
          filters:
            - RewritePath=/test/consul-client/?(.*), /

management:
  endpoints:
    web:
      exposure:
        include: "*"